version: '2'
volumes:
  pdb:
  redis:
services:
  web:
    build: .
    ports:
     - "3031:3031"
    depends_on:
     - db
    env_file: 
     - .env
  celery:
    build: .
    command: celery -A tasks worker --loglevel=info
  db:
    image: postgres:latest
    env_file:
     - .env
    volumes:
     - pdb:/var/lib/postgresql/data
  redis:
    image: 'redis:3.0-alpine'
    volumes:
      - redis:/data
