version: '2'
volumes:
  pdb:
  pn_rabbitmq:
services:
  web:
    build: .
    ports:
     - "3031:3031"
    depends_on:
     - db
    env_file: 
     - .env
  celery:
    build: .
    env_file: 
     - .env
    command: "dockerize -wait tcp://rabbitmq:5672 celery -A PhoenixNow.tasks worker --loglevel=info"
  db:
    image: postgres:9.5.4
    env_file:
     - .env
    volumes:
     - pdb:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.6.5
    volumes:
      - pn_rabbitmq:/var/lib/rabbitmq
